### PR TITLE
Feat/generic content block

### PR DESCRIPTION
**Pull request by Tiaan-CC**
# Context

[Link to Notion ticket](https://www.notion.so/cloudcannon/ca791fe40ea54f44b7d27ae0f753e4e6?v=f6e20178eb3945f0934be7468e7f9c72&p=e2ca3e9a16d34ab999c4810f66999871&pm=s) 

# Additional information
The component is called generic/rich-text

I haven't added the tailwind prose styling (suggested by Jan), but have the code for this if we decide to add this at a further date. 

# Testing (tester)

The reviewer should check on this branch:

- The code
- The component in Bookshop browser ( generic/rich-text ) 
- [The site in CloudCannon (link here)
](https://app.cloudcannon.com/42158/editor#sites/115938/dashboard/summary)
# Before merge (PR owner)

- Delete the test site in CloudCannon

### CODE REVIEW

**Review by Amber-Song — APPROVED** [review]
Looks great!

**Review by James-cloudcannon — COMMENTED** [review]
Might be something on my ends but I am not getting the correct format inside the component editor or the cloudvent link. Whats the expected output? The indenting and headings work but that's about it.

**Comment by AlyshaNolan** [comment]
This will be used inside the simple-text-block component

**Review by jtrbuhovic — APPROVED** [review]
Looks good!

**Review by AlyshaNolan — APPROVED** [review]

**Pull request merged**
