### PR TITLE
Refactor/component consistency

### PR DESCRIPTION
**Pull request by adon-cloudcannon**
# Context

[Link to Notion ticket](https://www.notion.so/cloudcannon/Component-consistency-4156b548f8d04b089481de5fba63fdb8)

# Additional information

- Reviewed all components - shortened names and descriptions
- Left/Right blocks all have 'Left/Right' removed
- Tags added to all components
- L/R blocks have unique icons where appropriate

# Testing (tester)

The reviewer should check on this branch:

- The code
- The component in Bookshop browser
- The site in CloudCannon [(link here)](https://app.cloudcannon.com/42158/editor#sites/119526/dashboard/summary:/edit?editor=visual&url=%2F&collection=pages)

# Before merge (PR owner)

- [ ] Delete the test site in CloudCannon
- [ ] For "generic" components **only**: remove `- content_blocks` from `structures` in the YAML file (this was added for testing).

### CODE REVIEW

**Comment by AlyshaNolan** [comment]
Should the component names match the labels?

**Comment by adon-cloudcannon** [comment]
@AlyshaNolan throw that over to the others maybe? I don't know... I can see why they should maybe... but also, thinking along the lines of separating form/function - they can be called things like Left-Right-featured-map... etc... and have a more concise 'user friendly' label? I think that's the separation of the dev side vs editor side?

But don't have strong opinions either way - depends how long you want to keep working on SBT I guess :P

**Comment by AlyshaNolan** [comment]
I think from our discussion we decided that they should mostly match but in the case of ones like left-right--featured-map we can label it Contact and the name can be left-right-contact

**Review by AlyshaNolan — CHANGES_REQUESTED** [review]
See comments

**Review by AlyshaNolan — CHANGES_REQUESTED** [review]
- Rename the simple gallery to image-gallery?

**Comment by adon-cloudcannon** [comment]
Random observation - the comment/helper text for Image Gallery > Images says "The images should be square in shape"... but this is slightly misleading, as the images will be cropped regardless... so... is this text really necessary? Or could be reworded or something?

**Review by AlyshaNolan — APPROVED** [review]

**Pull request merged**
