### PR TITLE
Fix/grid gallery images

### PR DESCRIPTION
**Pull request by adon-cloudcannon**
# Context

[Link to Notion ticket](https://www.notion.so/cloudcannon/Grid-gallery-images-comment-1818a4f7ec7348a092d3a2a042ff08d8)

# Additional information

- Made the button display in live editing regardless of the number of images
- Updated the note to reflect this; also clarified the 3-6 images thing...

# Testing (tester)

The reviewer should check on this branch:

- The code
- The component in Bookshop browser
- The site in CloudCannon [(link here)](https://app.cloudcannon.com/42158/editor#sites/119559/dashboard/summary:/edit?editor=visual&url=%2F&collection=pages&path=%2Fsrc%2Fpages%2Findex.html)

# Before merge (PR owner)

- [ ] Delete the test site in CloudCannon
- [ ] For "generic" components **only**: remove `- content_blocks` from `structures` in the YAML file (this was added for testing).

### CODE REVIEW

**Comment by Tiaan-CC** [comment]
Everything looks good to go except the button input. There is a button input that isn't being used, the actual load more button is hard coded with values. Fix ->  either remove this input and keep the button partial hard coded or use the button input and connect the button to live editing.

**Review by Tiaan-CC — CHANGES_REQUESTED** [review]
Everything looks good to go except the button input. There is a button input that isn't being used, the actual load more button is hard coded with values. Fix -> either remove this input and keep the button partial hard coded or use the button input and connect the button to live editing.

**Comment by adon-cloudcannon** [comment]
Probably a @AlyshaNolan question on how it's supposed to behave/look... I just made the button visible in live editing, the rest of the structure was already in place... 

My preference would probably be not a fully editable button as this is a special button that they can't change the arrow on, for example...? Not sure...

**Comment by AlyshaNolan** [comment]
Yep oversight on my part - they should be able to change the button text etc

**Review by Tiaan-CC — APPROVED** [review]
Changes look good!

**Pull request merged**
