### PR TITLE
Feat: create price list component

### PR DESCRIPTION
**Pull request by AlyshaNolan**
# Context

[Link to Notion ticket](https://www.notion.so/cloudcannon/Services-Lists-5f05d0a77fce497194a64de0e61c144d?pvs=4)

# Testing (tester)

The reviewer should check on this branch:

- The code
- The component in Bookshop browser
- The site in CloudCannon [link here](https://app.cloudcannon.com/42158/editor#sites/118023/setup)

# Before merge (PR owner)

- [ ] Delete the test site in CloudCannon

### CODE REVIEW

**Review by Amber-Song — APPROVED** [review]
This looks good to me!

**Review by calumocannon — COMMENTED** [review]
Nitpick text edge cases

Add `overflow-wrap: anywhere` instead of `break-word` ?

Screenshot 2023-10-31 at 3 54 50 PM

Screenshot 2023-10-31 at 3 40 55 PM

**Review by calumocannon — COMMENTED** [review]
I notice "light" gets an icon and "dark" doesn't :(

I assume that is off topic and is a bookshop thing ? if so ignore.

Screenshot 2023-10-31 at 4 31 30 PM

**Review by calumocannon — APPROVED** [review]
LGTM 🚢

**Pull request merged**
