### PR TITLE
Refactor/final figma checking

### PR DESCRIPTION
**Pull request by adon-cloudcannon**
# Context

[Link to Notion ticket](https://www.notion.so/cloudcannon/Final-check-of-design-against-Figma-7ca92b3d448d40fa86183c7004c35bb6)

# Additional information

- Big one... basically just check all the styles seem consistent and use the right variables and units.... 

# Testing (tester)

The reviewer should check on this branch:

- The code
- The component in Bookshop browser
- The site in CloudCannon [(link here)](https://app.cloudcannon.com/42158/editor#sites/119591/dashboard/summary:/edit?editor=visual&collection=pages&url=%2F)

# Before merge (PR owner)

- [ ] Delete the test site in CloudCannon
- [ ] For "generic" components **only**: remove `- content_blocks` from `structures` in the YAML file (this was added for testing).

### CODE REVIEW

**Comment by Amber-Song** [comment]
Don't know if it is matter, in the design, the nav is partly transparent and in the code it is totally black.
Screenshot 2023-12-15 at 2 10 00 PM

**Comment by Amber-Song** [comment]
Load more button is added in the editor but not shown up in the live site in image gallery component.
Screenshot 2023-12-15 at 2 25 46 PM

**Comment by Amber-Song** [comment]
When I try to edit description for grid item (icon list) and write the description start with number, it breaks the site. Don't know if it is a known issue.
Screenshot 2023-12-15 at 2 33 19 PM

**Comment by adon-cloudcannon** [comment]
The transparent nav was not done - the decision was made that this would be too hard to do when the nav and content_blocks are in completely separate sections... would be a lot of calculating heights and padding etc... so, it;s ok to be black :)

**Comment by adon-cloudcannon** [comment]
The load more button should only show in the live site if there are more than 6 images (desktop) - however, we show the button in the live editing always so that the editor can see it and change the text/style etc...

I think there should be a dev note explaining this? Hopefully it is still there?

**Comment by adon-cloudcannon** [comment]
Have pushed a fix for the number issue mentioned above :)

**Comment by Amber-Song** [comment]
> The load more button should only show in the live site if there are more than 6 images (desktop) - however, we show the button in the live editing always so that the editor can see it and change the text/style etc...
> 
> I think there should be a dev note explaining this? Hopefully it is still there?

Oh sorry. I overlooked the dev note.

**Comment by Amber-Song** [comment]
The image card content part have a different background color to make the card stand out, but it is not in the site.
Screenshot 2023-12-15 at 3 42 38 PM

**Comment by Amber-Song** [comment]
So as the icon card, the background color of the content is not different from the whole background color.
photo_2023-12-15 15 46 21

**Comment by Amber-Song** [comment]
The card and icon background color is controlled by style.

**Review by Amber-Song — APPROVED** [review]

**Pull request merged**
