### PR TITLE
Chore: added information about preprocessing step to README

### PR DESCRIPTION
**Pull request by adon-cloudcannon**
# Context

[Link to Notion ticket](https://www.notion.so/cloudcannon/README-part-2-9bfd4b74730743178c5d98053ce2b83f)

# Additional information

- Added info to README about prebuild step.

# Testing (tester)

The reviewer should check on this branch:

- The code
- The component in Bookshop browser
- ~~The site in CloudCannon (link here)~~

# Before merge (PR owner)

- [ ] Delete the test site in CloudCannon
- [ ] For "generic" components **only**: remove `- content_blocks` from `structures` in the YAML file (this was added for testing).

### CODE REVIEW

**Review by AlyshaNolan — CHANGES_REQUESTED** [review]
This looks great but do you think as this you could potentially add a few more comments to the fetch-theme-utils file on the technical details of how it works? So that a dev (even internally) could pick up this template and have to do minimal research to understand how the script works

**Review by AlyshaNolan — APPROVED** [review]
I've approved this but ideally color fixes gets merged before this

**Review by calumocannon — CHANGES_REQUESTED** [review]
The README changes look good 💯 

About these 50 other files changed... is this PR against the wrong branch or... ? Some of them seem to be formatting but others aren't

**Review by calumocannon — COMMENTED** [review]
Sorry I didn't see Alysha had already approved. I'll withdraw my changes requested status but this does strike me as odd all these changes going in to a ticket called "Chore: added information about preprocessing step to README"

**Review by calumocannon — APPROVED** [review]

**Comment by adon-cloudcannon** [comment]
@calumocannon lol... I can explain that one... think the merge of fix/color-fixes in here probably did that? This README PR is tied to some changes from another branch... that's sort of what Alysha's comment above was about: "I've approved this but ideally color fixes gets merged before this..." - so at some point I merged in color-fixes to this branch to make sure I had the most recent changes... seems there were many changes there... 

Chalk it up to a bit of rogue devving... (not QUITE as bad as pushing to main... but up there...)

**Pull request merged**
