### PR TITLE
Feat/gallery

### PR DESCRIPTION
**Pull request by AlyshaNolan**
# Context

[Link to Notion ticket](https://www.notion.so/cloudcannon/Instagram-Custom-Gallery-1cf10b86e5d94031aa14ae7b3b87e804?pvs=4)

# Testing (tester)

The reviewer should check on this branch:

- The code
- The component in Bookshop browser
- The site in CloudCannon ([link here](https://app.cloudcannon.com/42158/editor#sites/118691/collections/pages/:/edit?editor=visual&url=%2F&path=%2Fsrc%2Fpages%2Findex.html&collection=pages))

# Before merge (PR owner)

- [x] Delete the test site in CloudCannon
- [x] For "generic" components **only**: remove `- content_blocks` from `structures` in the YAML file (this was added for testing).

### CODE REVIEW

**Comment by adon-cloudcannon** [comment]
Empty images (e.g. adding an image to the gallery but not specifying the actual image URL or anything) breaks the build...

Probably should either:
- leave an empty space in the grid or
- ignore empty images and continue the grid with other images

**Comment by adon-cloudcannon** [comment]
~~Load more button doesn't seem to work as intended? Adding >6 images makes the button appear, but all the images are still showing in the grid (i.e. none are hidden...) - thus, clicking the load more button does nothing...~~

Fix pushed for this issue - check please :)

**Comment by AlyshaNolan** [comment]
Reviewed your change Adon - looks great. 
Realised it wasn't working on mobile so fixed that and added some logic for the build to not error when an image isn't provided - can you please check? 😊

**Comment by adon-cloudcannon** [comment]
Added: width 100% on tile container because it looked odd with broken images in the grid
- also a white border around the broken images as it isn't super clear what's happening (just looks like a big empty space otherwise)

**Review by adon-cloudcannon — APPROVED** [review]
All looking good now - final tweak was the alt in the 11ty shortcode

**Pull request merged**
