### PR TITLE
Feat: add sizes to images parent components

### PR DESCRIPTION
**Pull request by AlyshaNolan**
# Context

[Link to Notion ticket](https://www.notion.so/cloudcannon/Update-images-to-use-the-sizes-option-from-parent-components-b3adee1bd5b1403fbe49b5ba321de382?pvs=4)

# Testing (tester)

The reviewer should check on this branch:

- The code
- The component in Bookshop browser
- The site in CloudCannon ([link here](https://app.cloudcannon.com/42158/editor#sites/119730/collections/pages/))

# Before merge (PR owner)

- [ ] Delete the test site in CloudCannon

### CODE REVIEW

**Review by adon-cloudcannon — COMMENTED** [review]
- are the breakpoints correct? Vic's tablet kicks in at 480px and desktop at 769px
- on that point - you have grid-gallery-images at 769px for one of the breakpoints, but grid-gallery-cards is 768px
- should the size units switch from vw to px? (I actually don't know... so if this is the suggested approach, then ignore comment...)

**Comment by AlyshaNolan** [comment]
> * are the breakpoints correct? Vic's tablet kicks in at 480px and desktop at 769px
> * on that point - you have grid-gallery-images at 769px for one of the breakpoints, but grid-gallery-cards is 768px
> * should the size units switch from vw to px? (I actually don't know... so if this is the suggested approach, then ignore comment...)

- I just went with whatever breakpoints the size of the images was changing currently
- I switched all instances of 768 -> 769
- They should be vw because they are not a fixed pixel size on mobile generally

**Review by adon-cloudcannon — CHANGES_REQUESTED** [review]
Just officially tagging this as requesting changes so we don't forget... you were going to change the px in the sizes to vw I think?

- e.g. image_sizes:"(min-width: 1279px) 960px, 91vw" ?

**Review by adon-cloudcannon — APPROVED** [review]

**Comment by AlyshaNolan** [comment]
Yep - originally agreed but now thinking that they should stay px as on bigger screens images dont grow so can't be don proportionally to the vw

**Pull request merged**
