### PR TITLE
Fix/content block

### PR DESCRIPTION
**Pull request by Amber-Song**
# Context

Link to [Notion ticket](https://www.notion.so/cloudcannon/Content-Block-with-Headings-981e521bc156493a800f4a227dda5a70?pvs=4)

# Additional information

Nothing

# Testing (tester)

The reviewer should check on this branch:

- The code
- The component in Bookshop browser
- The site in CloudCannon ([link here](https://avid-sketchpad.cloudvent.net/))

# Before merge (PR owner)

- [ ] Delete the test site in CloudCannon
- [x] Delete the data from site

### CODE REVIEW

**Comment by AlyshaNolan** [comment]
From looking at the code I have a couple thoughts:
- Rename to simple-text-block to match the designs
- I think the description might be better as something like "Block of content with a header"
- Remove outer div and add the component class
- Stray closing div
- Allow alignment and colour options

**Comment by Amber-Song** [comment]
> Rename to simple-text-block to match the designs

Done

> I think the description might be better as something like "Block of content with a header"

Done

> Remove outer div and add the component class

Done

> Stray closing div

Done

> Allow alignment and colour options

Done

**Review by AlyshaNolan — APPROVED** [review]

**Comment by adon-cloudcannon** [comment]
Looking pretty good... just a few small changes to be made:
- as this is a component that the user can add directly, it should be moved from 'simple' to 'sections'
- the actual text block is not getting the right site styles - this is because the elements in here are standard HTML element (p, h1, h2 etc etc) but the rest of the site uses CSS variables for styling (--large-heading, --paragraph) - for example, this results in the h3 being the wrong size in this box... or the paragraph not having the same line-height as Vic's design... 
- the suggested fix is to explicitly define the necessary element level styles inside the component scss file... e.g. h3{ font-size: var(--medium-heading) } etc etc)

**Review by adon-cloudcannon — CHANGES_REQUESTED** [review]
See my comment :)

**Comment by Amber-Song** [comment]
> as this is a component that the user can add directly, it should be moved from 'simple' to 'sections'

Good point!

> the actual text block is not getting the right site styles - this is because the elements in here are standard HTML element (p, h1, h2 etc etc) but the rest of the site uses CSS variables for styling (--large-heading, --paragraph) - for example, this results in the h3 being the wrong size in this box... or the paragraph not having the same line-height as Vic's design...
> the suggested fix is to explicitly define the necessary element level styles inside the component scss file... e.g. h3{ font-size: var(--medium-heading) } etc etc)

I changed the line-height for h3.

**Review by adon-cloudcannon — APPROVED** [review]

**Review by AlyshaNolan — APPROVED** [review]

**Pull request merged**
